### PR TITLE
Handle nested anchors in validation expansion (Fixes #273)

### LINKED ISSUE #273: Anchor on property which uses alias fails validation
Schema: 
```json
{
  "title": "Field definitions schema!",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {
    "field": {
      "type": "object",
      "additionalProperties": false,
      "required": ["label"],
      "properties": {
        "label": { "type": "string" }
      }
    },
    "model": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "props": {
          "type": "object",
          "additionalProperties": { "$ref": "#/definitions/field" }
        }
      }
    }
  },
  "type": "object",
  "additionalProperties": { "$ref": "#/definitions/model" }
}

```

Document:
```yaml
Named:
  props: &NamedProps
    name:
      label: Name

Timestamped:
  props: &TimestampedProps
    <<: *NamedProps
    ts:
      label: Timestamp

Record:
  props:
    <<: *TimestampedProps # commenting out this line removes the errors
    id:
      label: ID
```
Looks like it's incorrectly adding a layer of nesting or something?

Screenshot 2020-07-08 20 25 57 Screenshot 2020-07-08 20 25 51

### PR DESCRIPTION
**Pull request by metcalf**
### What does this PR do?
Primarily, this adds support for recursively expanding multiple levels of aliases. In the process I made some other minor changes:
* `validateTextDocument` was swallowing errors which made my test pass when it should have failed. I think propagating errors could result in "unhandled promise rejection" errors in logs but I think that's better than ignoring them?
* Double-negative typos in a few tests I saw
* I added a test for a very particular case of anchor error rendering. I initially thought this was broken, but it appears intentional so I wanted to encode it in a test since it seems easy to regress.

### What issues does this PR fix or reference?
#273

### Is it tested? How?
Wrote a test. Ran this in development against a YAML file/schema that was giving me trouble.

### CODE REVIEW

File: src/languageserver/handlers/validationHandlers.ts [hunk 1]
```diff
@@ -51,24 +51,19 @@ export class ValidationHandler {
...
-          const removeDuplicatesDiagnostics = removeDuplicatesObj(diagnostics);
-          this.connection.sendDiagnostics({
-            uri: textDocument.uri,
-            diagnostics: removeDuplicatesDiagnostics,
-          });
-          return removeDuplicatesDiagnostics;
-        },
-        () => {
-          return [];
+      .then((diagnosticResults) => {
```
Comment (metcalf) [inline src/languageserver/handlers/validationHandlers.ts:54]: Review with `?w=1` if you want to confirm no semantic changes other than not swallowing the promise rejection.

**Review by evidolob — APPROVED** [review]
Working good. Not sure about swallowing promise rejection in `validateTextDocument`, maybe @JPinkney has some points.

**Review by JPinkney — APPROVED** [review]
I think we were swallowing errors because i'm not sure how other language clients respond to being sent an "unhandled promise rejection". vscode-json-languageservice seems to not swallow them so I'm OK with the change
