### PR TITLE
Fix completion indentation for object in array

### LINKED ISSUE #329: Bug: autogenerated snippet for keys that contain an array of objects is badly indented
When I validate auto-completion for a key that contain an array of objects, the snippet generated contains 2 extra spaces for each sub-key generated.

Here's an example in `kubernetes.yml`:

Given that I have this file content:
```
metadata:
    ownerReferences
```
Then I go to end of `ownerReferences`, press `Ctrl+Tab` and `[ENTER]` to validate the suggested completion.  
I get this result:
```
metadata:
    ownerReferences:
        - apiVersion: 
            kind: 
            name: 
            uid: 
```

The problem is that "kind", "name" and "uid" keys have 2 extra spaces in front.

### PR DESCRIPTION
**Pull request by evidolob**
This is firs PR, fix completion snippet generation for object in array. We also have problem with settings synchronisation, in case if `editor.tabSize` set up in language scope `[yaml]` we not take in account it. This PR fix that, but it also requires fix in `vscode-yaml` which I'm going to provide.

For #329

### CODE REVIEW

File: src/server.ts [hunk 1]
```diff
@@ -511,7 +511,9 @@ connection.onDidChangeConfiguration((change) => {
 
   schemaConfigurationSettings = [];
 
-  if (settings.editor?.tabSize) {
+  if (settings['[yaml]'] && settings['[yaml]']['editor.tabSize']) {
+    indentation = ' '.repeat(settings['[yaml]']['editor.tabSize']);
```
Comment (JPinkney) [inline src/server.ts:515]: Should we document this somewhere just so people know that if their editor supports yaml specific tabSizes then it takes precedence over the regular editor.tabSize

**Review by JPinkney — APPROVED** [review]
Tested it out and it works well

File: src/server.ts (hunk 1 above)
Comment (evidolob) [reply src/server.ts:515]: Hm, not sure, do we have some description of settings that we use ?

Comment (JPinkney) [reply src/server.ts:515]: We only really have https://github.com/redhat-developer/yaml-language-server#language-server-settings but since the number of spaces is grabbed from editor.tabSize we should probably add a little writeup there. I can do it in a separate PR if you want

Comment (evidolob) [reply src/server.ts:515]: Yes, that helps, pleas include also `proxy` and `proxyStrictSSL` settings usage

File: src/languageservice/services/yamlCompletion.ts [hunk 2]
```diff
@@ -149,7 +149,7 @@ export class YAMLCompletion extends JSONCompletion {
           suggestion.label = label;
           proposed[label] = suggestion;
           result.items.push(suggestion);
-        } else if (!existing.documentation) {
+        } else if (!existing.documentation && suggestion.documentation) {
```
Comment (joshuawilson) [inline src/languageservice/services/yamlCompletion.ts:152]: How is this related? How is it tested?

File: src/languageservice/services/yamlCompletion.ts [hunk 3]
```diff
@@ -260,7 +260,7 @@ export class YAMLCompletion extends JSONCompletion {
     addValue: boolean,
     separatorAfter: string,
     collector: CompletionsCollector,
-    document
+    document: TextDocument
```
Comment (joshuawilson) [inline src/languageservice/services/yamlCompletion.ts:263]: Did you know that `TextDocument` is deprecated?

File: src/languageservice/services/yamlCompletion.ts [hunk 4]
```diff
@@ -797,12 +792,7 @@ export class YAMLCompletion extends JSONCompletion {
         break;
       case 'object':
         {
-          const objectInsertResult = this.getInsertTextForObject(
-            schema,
-            separatorAfter,
-            `${indent}${this.indentation}`,
-            insertIndex++
-          );
+          const objectInsertResult = this.getInsertTextForObject(schema, separatorAfter, `${this.indentation}  `, insertIndex++);
```
Comment (joshuawilson) [inline src/languageservice/services/yamlCompletion.ts:795]: Do you need to also make this change for line 736 above?

File: src/languageservice/services/yamlCompletion.ts (hunk 3 above)
Comment (evidolob) [reply src/languageservice/services/yamlCompletion.ts:263]: Yes, but we use it across all project.

File: src/languageservice/services/yamlCompletion.ts (hunk 4 above)
Comment (evidolob) [reply src/languageservice/services/yamlCompletion.ts:795]: No

**Review by joshuawilson — APPROVED** [review]
